In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/fraudTrain.csv")
df = df.drop(columns=['Unnamed: 0'])
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
df['dob'] = pd.to_datetime(df['dob'])
df.shape

(1296675, 22)

In [4]:
df['hour']= df['trans_date_trans_time'].dt.hour
df['day_of_week'] = df['trans_date_trans_time'].dt.dayofweek
df['is_night'] = df['hour'].isin([22,23,0,1,2,3]).astype(int)

In [5]:
df['age']= (df['trans_date_trans_time'] - df['dob']).dt.days // 365

In [7]:
df = df.sort_values(['cc_num','trans_date_trans_time'])
df['cc_txn_total_count'] = df.groupby('cc_num').cumcount() + 1
df['cc_avg_amt'] = df.groupby('cc_num')['amt'].transform(lambda x : x.expanding().mean().shift(1))
df['amt_vs_cc_avg'] = df['amt'] / df['cc_avg_amt']

In [9]:
df[['cc_num', 'trans_date_trans_time', 'amt', 'cc_txn_total_count', 'cc_avg_amt', 'amt_vs_cc_avg']].head(10)

,cc_num,trans_date_trans_time,amt,cc_txn_total_count,cc_avg_amt,amt_vs_cc_avg
1017,60416207185,2019-01-01 12:47:15,7.27,1,NaN,NaN
2724,60416207185,2019-01-02 08:44:57,52.94,2,7.270000,7.281981
2726,60416207185,2019-01-02 08:47:36,82.08,3,30.105000,2.726457
2882,60416207185,2019-01-02 12:38:14,34.79,4,47.430000,0.733502
2907,60416207185,2019-01-02 13:10:46,27.18,5,44.270000,0.613960
4135,60416207185,2019-01-03 13:56:35,6.87,6,40.852000,0.168168
4337,60416207185,2019-01-03 17:05:10,8.43,7,35.188333,0.239568
5467,60416207185,2019-01-04 13:59:55,117.11,8,31.365714,3.733695
6027,60416207185,2019-01-04 21:17:22,26.74,9,42.083750,0.635400
6273,60416207185,2019-01-05 00:42:24,105.20,10,40.378889,2.605322

In [10]:
df['mins_since_last_txn'] = df.groupby('cc_num')['trans_date_trans_time'].diff().dt.total_seconds() / 60

In [11]:
df[['cc_num', 'trans_date_trans_time', 'amt', 'mins_since_last_txn']].head(10)

           cc_num trans_date_trans_time     amt  mins_since_last_txn
1017  60416207185   2019-01-01 12:47:15    7.27                  NaN
2724  60416207185   2019-01-02 08:44:57   52.94          1197.700000
2726  60416207185   2019-01-02 08:47:36   82.08             2.650000
2882  60416207185   2019-01-02 12:38:14   34.79           230.633333
2907  60416207185   2019-01-02 13:10:46   27.18            32.533333
4135  60416207185   2019-01-03 13:56:35    6.87          1485.816667
4337  60416207185   2019-01-03 17:05:10    8.43           188.583333
5467  60416207185   2019-01-04 13:59:55  117.11          1254.750000
6027  60416207185   2019-01-04 21:17:22   26.74           437.450000
6273  60416207185   2019-01-05 00:42:24  105.20           205.033333